language: node_js
sudo: required
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
script:
  - xvfb-run polymer test
